### ISSUE TITLE
Debug help

### ISSUE THREAD

**Issue by Abc11c** [kakaobrain/leco#2]
1. Resolved with the right version of torch (1.9.0)

[Resolved]
Hi @twidddj , I was trying to reproduce the results from the paper for minigrid envs, followed the instructions in readme and got the following error. 

`python -m dist.launch --nnodes=1 --node_rank=0 --nproc_per_node=2 --master_addr=$MASTER_ADDR -m sample_factory.algorithms.appo.train_appo --cfg=lstm_MiniGrid-ObstructedMaze-Full_leco --train_dir=/your/train/directory --experiment=your_experiment_name`

Kindly help debug the same! 

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/user/.conda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/.conda/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/working/leco/sample_factory/algorithms/appo/learner.py", line 1965, in _train_loop
    self._process_training_data(data, wait_stats)
  File "/home/user/working/leco/sample_factory/algorithms/appo/learner.py", line 1890, in _process_training_data
    train_stats = self._train(buffer, batch_size, experience_size)
  File "/home/user/working/leco/sample_factory/algorithms/appo/learner.py", line 1209, in _train
    loss.backward(retain_graph=True)
  File "/home/user/.conda/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/user/.conda/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [768, 64, 6, 6]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

Thanks!

**Comment by Abc11c** [comment]
2. How to debug ?
Is there any way to run the processes (threads) synchronously instead of the async version? 
like the ones here from the latest [sample-factory](https://www.samplefactory.dev/07-advanced-topics/serial-mode/?h=debug) repo?
